spring.application.name=bars
spring.data.mongodb.uri=mongodb://localhost:27017/test_db
security.jwt.secret=VGhpc0lzQVNlY3VyZUFuZEhTZTI1NktleUZvckJhcnNQcm9qZWN0MTIzNDU2Nzg5MA==
security.jwt.expiration-ms=86400000
